### ISSUE TITLE
Bencode_streaming.Encode fails on min_int

### ISSUE THREAD

**Issue by stedolan** [rgrinberg/bencode#4]
```
# Bencode_streaming.Encode.to_string (Bencode.Integer min_int);;
Exception: Invalid_argument "String.blit / Bytes.blit_string".
```

(seems to be just Bencode_streaming, Bencode.encode_to_string works fine)

**Comment by c-cube** [comment]
Interesting. Because `- min_int` is `min_int`, the log10 of `- min_int` is negative and leads to a wrong estimation of the length it will take once displayed.
