### ISSUE TITLE
Test suite fails (QCheck seems to have changed)

### ISSUE THREAD

**Issue by cfcs** [rgrinberg/bencode#5]
Hey, I just tried to run the test suite, but it didn't compile.

I wanted to create some torrent files and needed a bencode module for the serialization.
I am not sure if this module is abandoned and I should look elsewhere (if is not abandoned I'll make a PR to fix the tests).

Ping @rgrinberg

**Comment by rgrinberg** [comment]
Its not abandoned but not really maintained either. Feel free to help with
maintenance. I doubt bencode changed much over time, so I don't think you
will have problems bringing it to a usable state.

**Comment by cfcs** [comment]
Ah, it seems @c-cube has already fixed it: https://github.com/c-cube/bencode/commit/b40c3e57df8d930365388255767b867d630d55fc
